### ISSUE TITLE
Sphinx doesn't load contacts/tribes on boot up

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#111]
**Task**

Multiple people have experienced the following bug. On first boot up, the Tribes and Friends don't show up, until the user searches.

However, sometimes Sphinx doesn’t sync contacts when quitting the app and therefore have to restore

Occasionally crashes, where they have to remove account, delete app, then restore for it to load contacts.

![Image](https://user-images.githubusercontent.com/142233216/265453396-71719457-4fd6-4df9-abcd-a40104a03469.png)

![Image](https://user-images.githubusercontent.com/142233216/265936774-2dcbb619-fc59-4057-aef0-d26e193d9b60.png)

**Comment by tomastiminskas** [comment]
@tomsmith8 this issue has been affecting Paul for weeks and I wasn't able to reproduce it. But yesterday I found a way and I released version 285 with some changes that prevents it. At least Paul confirmed it was working well in his first attempts. Can you confirm if it's fixed in build 285 or still happening to some users?

**Comment by tomsmith8** [comment]
@tomastiminskas Interesting thanks - I'll close this ticket and reopen it if we see another reported case!

Note: It works for me and unable to recreate currently on 285
