### ISSUE TITLE
display budget in mac app

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-mac#15]
In the webview we probably want to find a way to display a budget if one is set in the webview

**Comment by kevkevinpal** [comment]
This is when they're in secondbrain, sphinx-bridge sets a budget in the mac app in the webview to restrict the number of sats the website can send from their node

**Comment by kevkevinpal** [comment]
com.stakwork.sphinx.desktop/Scenes/Dashboard/WebApps/Helper/WebAppHelper.swift

I think this is the file where we're doing some of the logic

**Comment by jimBeaux27** [comment]
@tomastiminskas  Ok. I am looking at this and it's the first time I'm touching it. I notice a few problems:
![image](https://user-images.githubusercontent.com/96802642/234919831-accc5f3e-1f31-4cd9-9335-8dea5a147403.png)
![image](https://user-images.githubusercontent.com/96802642/234920619-09be7a84-2705-416e-936b-1a697ba6dcbf.png)


1. The server doesn't seem to be returning a response for budget amount like the client seems to expect. Could it be that the back end changed somehow without a requisite change to the client? (first photo)
2. I am not sure if this is expected behavior but I notice the authorize sats view is pushed all the way to the back of the UI (second photo)
3. The app itself crashes when I try to run a search. This is the first time I've really tried to do a 2nd brain search. Has someone else QA tested & passed this functionality or am I doing something wrong? (first photo)

Jim

**Comment by jimBeaux27** [comment]
NVM it was issues on my Xcode instance for some reason...

I just pushed out a PR for this #80
