### ISSUE TITLE
Unable to Open Sphinx on Mac

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#154]
Unable to Open Sphinx on Mac due to this error:

- No option to Update
- Opening causes these two popup windows

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/8ac7968b-e1b5-47eb-a310-6818e717c7a5)

**Comment by tomsmith8** [comment]
Deleting Sphinx and redownloading has fixed the issue..

Would be a good one to keep tracking and to investigate

**Comment by tomastiminskas** [comment]
@tomsmith8 I didn't find anything about this issue when installing app from Test Flight, but this error code it's usually related with permissions of the app. So I would say it's more like a Test Flight issue than a Sphinx app issue, because distribution is done by TF app automatically. Let's just keep an eye on it to see if someone else report it.
