### ISSUE TITLE
Failed messages in sidebar but not in tribe

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#334]
Report from Paul:

"I’ve noticed these red failed message alerts sometimes on boosts specifically
i’ll try to find a pattern, but it msg shows fine in the tribe itself, the issue seems to be on the notification in the sidebar"

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/0ebd7c00-09c9-4505-8307-8d5d7ec11663)

**Comment by tomsmith8** [comment]
Recreated by boosting Kevins msg in Planet Sphinx:


![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/11a441bd-5e45-4996-a8eb-c16539e757ac)

**Comment by tomsmith8** [comment]
^^
happened to me - maybe an issue with a huge tribe...

or a full node user (in this case Kevin..) - they’re to two variables I’m thinking atm

**Comment by tomastiminskas** [comment]
@tomsmith8 working on this one. I could reproduce it. Basically what happens is that if the destination of the boost can't be reached (because of no route to destination for example) the boost will show as failed on the chats list but it will show as succeeded in the message row. I will apply this to both iOS and Mac

**Comment by tomsmith8** [comment]
Great, thanks Tom!
