### ISSUE TITLE
remove all popup windows in Sphinx and add slide in left panel

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#336]
**Task**

When doing certain actions in Sphinx, it pops a bunch of new windows stacked on top of each other:

- Edit tribe
- Share tribe QR 

This results in main sphinx, plus 2 pop ups.

Simple v1 should slide in from the left

Current:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/35367933-02bf-439b-89a0-53a958e8b68f)

New:

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/778145bf-608c-4a76-a12f-559baa275472)

**Comment by Antanasijevic** [comment]
Here is navigation, based purely on screenshot of existing UI.
We have explored side panel Layout for Threads in this ticket #165  so i suggest we use the same approach.
For v2, It may be a good idea if we consider adding some minor changes to improve overall experience, i can provide some samples so we can discuss it. 
Also, if you think it may be useful, maybe i could flush out all major actions for desktop version (Editing profile, adding friends, creating tribes, etc...) so we can use it as a blueprint for future improvements.   

https://github.com/stakwork/sphinx-mac/assets/13258550/8dfadb50-2d17-42b9-a08d-35ed9e106cd8

**Comment by tomsmith8** [comment]
@tomastiminskas for a v1 improvement (keeping everything inside the screen without windows).

Thoughts on this right side panel approach?

**Comment by tomastiminskas** [comment]
@tomsmith8 @Antanasijevic looks great. I would say that if we want to bounty this we should do it by screen. For example this one could be a first ticket (Tribe details and Edit/Share tribe). 

I can provide details or some guidance on how to implement this once we have a ticket. 

My only concern is how to handle this for tribes with Podcast, since the player shows in that exact same place (right side of the chat). So maybe Tribe details/Edit/Share should show up on top of the player, then show the player again when dismissed. Thoughts?

**Comment by Antanasijevic** [comment]
@tomastiminskas @tomsmith8 Before we bounty out this, i believe it would be useful if i could make a quick wireframe or mockup, including all current scenarios and combinations, so we can discuss technical possibilities, and have a blueprint for future improvements. It doesn't have to take long for me to do it  but may be very useful. 
Overall, a proper combinations of side panel and pop ups will work.
In the case of podcast, we can probably minimize podcast on the bottom right once edit panel is opened, or something similar.

Additionally, whenever you think it is a good time, we can polish UI and make it more clear and intuitive. Here is a quick mockup i did with this in mind

![image](https://github.com/stakwork/sphinx-mac/assets/13258550/4c1b6a5e-5142-45fa-89d5-4515611ce8a5)

**Comment by Antanasijevic** [comment]
@tomastiminskas @tomsmith8 When it comes combinations of Podcast and Edit panel, something like this may work, but i need to look into desktop navigation more carefully.



https://github.com/stakwork/sphinx-mac/assets/13258550/92ea2496-f05c-4970-8833-c1ef58c00e48

**Comment by tomsmith8** [comment]
> So maybe Tribe details/Edit/Share should show up on top of the player, then show the player again when dismissed. Thoughts?

Yeah I think this would be the best v1 solution for now and massively improves UX with multiple windows.

Let's use the right panel as a popover window. 

The areas that need this are:

- View Tribe Details/Edit/Share
- My Profile
- View User details/share pubkey

Transactions:

- As transactions is on the bottom left, I think a pup UP on press to cover chats would be nice.

Are there any other actions that causes windows to pop?

**Comment by tomastiminskas** [comment]
Here are all the views that causes a window to pop up:

I think these 2 should open on a right side panel as in the video Milan posted since they are supplementary to the chat view
- View Tribe Details/Edit/Share
- View User details/share pubkey

In the other hand the following view are main views not related with a specific chat so maybe they should replace the chat view when showing up
- My Profile
- New Contact / New Invite
- Create Tribe
- Transactions
- Create/Pay Invoice (from chats list bottom bar)

@tomsmith8 @Antanasijevic

**Comment by tomsmith8** [comment]
@Antanasijevic - Let's get a v1 design for:

View Tribe Details/Edit/Share
View User details/share pubkey

We can then bounty that out to start while working on the other features

**Comment by Antanasijevic** [comment]
@tomsmith8 Here are few notes regarding Desktop navigation with a video preview. Please let me know what you think.

**Right Panel** 
Right Panel should be reserved for all the details related to currently active chat/tribe, which includes
- Tribes : Tribe details / Edit / Share / Member info / Threads / Badges
- User : Edit / Share 

Tribes with podcast, are only situation that i am aware of when two side panels should be present in same time, but we can solve that by collapsing player when other side panel is opened. 

**Main Menu**
I suggest we group all main actions in main menu drop down, similar to one we have in mobile app. 

**Pop ups**
Pages like Profile, Transactions, Request payment, Pay Invoice, Create Tribe, Invite member, can open as a pop up.
We should make sure to always have only one pop up at a time.
Ideally, we can think about making pop up show in parent window, not as a separate window.


https://github.com/stakwork/sphinx-mac/assets/13258550/8d887b0a-76b1-4ddd-bced-7c5dd063e6fc

**Comment by tomsmith8** [comment]
This is nice.

Waht do you reckon @tomastiminskas ? We can break each of these down and bounty them out.

**Comment by tomastiminskas** [comment]
@tomsmith8 @Antanasijevic the video looks amazing and I think it will make everything much easier for the user. I few things to consider:

- Definitely we can break these down into bounties but we should solve the issue about designs details, since most of the hunters doesn't have access to Sigma project and if they don't have a details reference they make layouts with different colors, dimensions, etc so then I have to take care of them. Not a problem for me, but if we want hunters to take care of everything we should give them access or provide them with something else (any ideas about this @Antanasijevic ?)
- I would leave the collapsed podcast player out of the bounties and I can take care of it. The podcast player is complex and making the collapsed view to update while podcast is playing can be challenging so I would prefer to take that my self and prevent future bugs.
- The main menu on the left column is definitely a good first bounty and I would divide that into 2 bounties: 1 for making the menu layout and linking that with opening the current windows for profile, contacts, etc. A second one for implementing those views on top of the main window with the blurred background as on the video

Let me know your thoughts

**Comment by Antanasijevic** [comment]
@tomsmith8 On this link you can find layouts for side panel, including Tribe info, Edit tribe, Share tribe, Thread list and thread.
In also contains same screens with podcast mini player included on the bottom.

Figma project
https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3378%3A20203&mode=design&t=q92a1qyS3Vs4ebzE-1

Prototype without podcast
https://www.figma.com/proto/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3378-26349&t=flL1GOeaJGv6fmlp-1&scaling=min-zoom&page-id=3378%3A20203&starting-point-node-id=3378%3A26349&show-proto-sidebar=1&mode=design



https://github.com/stakwork/sphinx-mac/assets/13258550/677daf59-5a6d-4656-a261-e3bd7927d4ad






Prototype with podcast
https://www.figma.com/proto/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3378-20204&t=flL1GOeaJGv6fmlp-1&scaling=min-zoom&page-id=3378%3A20203&starting-point-node-id=3378%3A20204&show-proto-sidebar=1&mode=design



https://github.com/stakwork/sphinx-mac/assets/13258550/a304fc51-55c2-489b-90c6-4035e2910e5e



When Collapsing podcast to mini player, ideally we should have some kind of transition, similar to this one. Let's discuss options.

https://github.com/stakwork/sphinx-mac/assets/13258550/9ff96d38-eb49-4a4d-9220-88a1cf87a56a

**Comment by Antanasijevic** [comment]
@tomsmith8 I have moved Main menu as a separate issue here 
https://github.com/stakwork/sphinx-nav-fiber/issues/1195

**Comment by Antanasijevic** [comment]
@tomsmith8 I have also moved Pop up layout improvements for V1 to separate issue here #356

**Comment by Antanasijevic** [comment]
@tomsmith8 If no change is needed, final layouts can be found here 
https://www.figma.com/file/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?type=design&node-id=3378%3A20203&mode=design&t=KwHixq2mJSAG9lCV-1
