### ISSUE TITLE
Improve sharing own Public Key

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-mac#404]
Improve and reduce the steps to share you own public key.

Right now it requires:
1. Tapping on hamburger icon to open Menu
2. Going to Profile
3. Tapping on QR code icon next to you public key
4. Tapping copy to share

**Comment by Antanasijevic** [comment]
@tomastiminskas What do you think about adding "Share Pubkey" button in main menu, next to "Add Friend" and "Create Tribe"?
Adding qr code next to refresh will create a clutter and may not be quite clear.
This way we can make a clear action, and i believe this is proper place.

![Image](https://github.com/stakwork/sphinx-mac/assets/13258550/3e7d9734-30b2-4dcd-bdbe-e7c3862e0166)

**Comment by tomastiminskas** [comment]
@Antanasijevic it's better that the current way of sharing your public key, but still a few steps:
1. Openning Menu
2. Tapping on new button
3. Tapping on copying or making screenshot of the QR code

Any way we can try to add a direct button/icon somewhere in the header that will take directly to the QR code view?  If you can come up with something like that I can then review with Paul and decide.

**Comment by Antanasijevic** [comment]
@tomastiminskas As we discussed, the only way of having Pubkey pop up one click away is to place an icon next to refresh and hamburger icon, since this is most convenient place. Tooltip may be handy in situations like this.

![image](https://github.com/stakwork/sphinx-mac/assets/13258550/27fdba82-4afc-459c-8657-d40e5621514c)


In addition to icon on top, i suggest we add one more way to share contact, placed in main menu.
That way, we can have alternative in case profile area becomes too cluttered.

We can have "Share Pubkey" button next to "Add Friend" and "Create Tribe" buttons in main menu, grouping these three similar functions together. 

![image](https://github.com/stakwork/sphinx-mac/assets/13258550/d8c80170-f10d-4cc1-8f66-3e40bf57befc)


As a variation of previous option, we can have a box with "Copy" button, as a shortcut,
while clicking on the remaining area of the box would open Pubkey pop up.

![image](https://github.com/stakwork/sphinx-mac/assets/13258550/583ce3bc-32de-476b-bf6f-cd8c02fd1eba)

**Comment by tomastiminskas** [comment]
@pitoi please review this whenever you can and let us know your thoughts. We can jump on a call to discuss if needed

**Comment by Antanasijevic** [comment]
@tomastiminskas Figma link https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4840-150880&t=m9IzZZ6iU1ulUz5v-1

**Comment by pitoi** [comment]
the overall goal is to connect to another user who's already on sphinx
THey can paste or scan:
 - the user can copy & paste their code and send it via text or email to their friend
 - the user's friend can scan their QR code or they can scan their user's code
 
I think 2 clicks is ok:
-  Tap "Connect with Friend" or tap the QR code next to the user's name on the upper left. (let's avoid new terms like Pubkey). This should be a common action that we don't want to bury under the menu or profile.
-  Display the QR code and display the option to tap to copy the QR code to the clipboard

**Comment by Antanasijevic** [comment]
![Image](https://github.com/stakwork/sphinx-mac/assets/13258550/f7c17597-72a8-444f-897d-cfa831629cd5)

**Comment by Antanasijevic** [comment]
@tomastiminskas here is Figma link where i separated final layout
https://www.figma.com/design/suipHjIGKg38rbWo0qHGqV/Desktop-Design-System---Dark-Version?node-id=4869-24500&t=IboidAedhw2iEoKI-1
